name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Use the latest stable version of the checkout action

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r docs/requirements.txt  # Install dependencies from the requirements.txt in the docs folder

    # Build the documentation with Sphinx
    - name: Build Docs with Sphinx
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"  # Specify the folder where the docs are located
        build-command: "sphinx-build -b html docs/ _build"  # Build the HTML documentation

    # Publish built docs to gh-pages branch
    - name: Commit documentation changes
      run: |
        git clone --branch gh-pages https://github.com/elijahmanda/symbolic-docs.git gh-pages  # Clone the gh-pages branch
        cp -r _build/html/* gh-pages/  # Copy the generated HTML files to the gh-pages directory
        cd gh-pages
        touch .nojekyll  # To avoid GitHub from trying to process the HTML files
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true  # Skip if no changes
        git push origin gh-pages  # Push changes to the gh-pages branch
